shit_shirt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ss_main.urls', namespace='ss_main')),
    path('users/', include('ss_users.urls', namespace='ss_users')),
]

ss_main/urls.py
from django.urls import re_path, path

from . import views

app_name = 'ss_main'

urlpatterns = [
    re_path(r'^$', views.main, name='main'),
    path('shirt/id<shirt_id>', views.shirt, name='shirt'),
    path('shirt/edit/id<shirt_id>', views.edit_shirt, name='edit_shirt')
]

ss_users/urls.py
from django.urls import re_path, path

from . import views

app_name = 'ss_users'

urlpatterns = [
    path('id<str:user_id>/', views.user_page, name='user_page'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('email/', views.email, name='email'),
    path('activate/uid=<str:uid>/token=<str:token>/', views.activate_user_email, name='activate'),
]

ss_main/models.py
from django.db import models
from ss_users.models import SSUser


class Shirt(models.Model):
    title = models.CharField(max_length=32)
    # file
    gender = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    base_colors = (
        ('wt', 'white'),
        ('bk', 'black'),
        ('rd', 'red'),
        ('gn', 'green'),
        ('bl', 'blue')
    )
    themes = (
        ('none', 'none'),
        ('love', 'love'),
        ('humor', 'humor'),
        ('trip', 'trip'),
        ('fear', 'fear'),
        ('night', 'night'),
        ('sadness', 'sadness'),
        ('disco', 'disco'),
        ('fog', 'fog')
    )
    base_color = models.CharField(max_length=2, choices=base_colors, default='wt')
    sex = models.CharField(max_length=1, choices=gender, default='M')
    theme = models.CharField(max_length=8, choices=themes, default='none')
    description = models.TextField(max_length=256)
    tegs = models.TextField(max_length=256, blank=True, null=True)
    creator = models.ForeignKey(SSUser, on_delete=models.DO_NOTHING, null=True)
    rating = models.DecimalField(decimal_places=2, max_digits=3)
    created = models.DateTimeField(auto_now_add=True)
    value = models.rating = models.DecimalField(decimal_places=2, max_digits=8, default=0)


class Comment(models.Model):
    text = models.TextField(max_length=1024, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(SSUser, on_delete=models.DO_NOTHING, null=True)
    shirt = models.ForeignKey(Shirt, on_delete=models.CASCADE, null=True)

ss_users/models.py
from django.db import models
from django.contrib.auth.models import User


class SSUser(User):
    confirm_email = models.BooleanField(default=False)
    rating = models.DecimalField(decimal_places=1, max_digits=2, default=0)
    achivements = models.CharField(max_length=64, default='')
    likes = models.IntegerField(default=0)

    class Meta:
        verbose_name = 's/s user'
        verbose_name_plural = 's/s users'

ss_main/views.py
from django.shortcuts import render
from .models import Shirt
from django.urls import Resolver404
from django.http import Http404


def main(request):
    three_shirts = []
    row = 0
    col = 0
    shirts = Shirt.objects.all()
    for shirt in shirts:
        if col == 0:
            three_shirts.append([shirt])
            col += 1
        elif col == 2:
            three_shirts[row].append(shirt)
            col = 0
            row += 1
        else:
            three_shirts[row].append(shirt)
            col += 1

    return render(request, 'main.html', {'shirts': three_shirts})


def shirt(reqiest, shirt_id):
    try:
        shirt = Shirt.objects.get(id=shirt_id)
    except Resolver404:
        Http404
    return render(reqiest, 'shirt.html', {'shirt': shirt})


def edit_shirt(reqiest, shirt_id):
    try:
        shirt = Shirt.objects.get(id=shirt_id)
    except Resolver404:
        Http404
    return render(reqiest, 'edit_shirt.html', {'shirt': shirt})

ss_users/views.py
from django.shortcuts import render
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.decorators import login_required
from django.utils.encoding import force_text

from . import logics, models, confirm_email
from ss_main.models import Shirt


def email_required(func):
    def wrapper(request, user_id=None):
        if not models.SSUser.objects.get(username=request.user.username).confirm_email:
            return email(request)
        else:
            return func(request, user_id)

    return wrapper


@login_required(login_url='users/login')
@email_required
def user_page(request, user_id=None):
    if not user_id:
        user_id = request.user.id
    user = models.SSUser.objects.get(id=user_id)
    shirts = Shirt.objects.filter(creator=user)

    return render(request, 'user_page.html', {'user': user, 'shirts': shirts})


def login(request):
    message = 'Good day, we are glad to see you.'
    if request.method == 'POST':
        user = auth.authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            message = 'The username or password were incorrect.'
        else:
            if not user.is_active:
                message = 'The account has been disabled, confirm your email.'
            else:
                auth.login(request, user)
                return HttpResponseRedirect('/')
    return render(request, 'login.html', {'message': message})


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def registration(request):
    message = logics.full_check(request)
    if not message:
        new_user = models.SSUser(username=request.POST['username'], email=request.POST['email'])
        new_user.set_password(request.POST['password1'])
        new_user.save()
        user = auth.authenticate(username=new_user.username, password=request.POST['password1'])
        auth.login(request, user)
        return email(request)

    return render(request, 'registration.html', {'message': message})


def email(request):
    user = models.SSUser.objects.get(username=request.user.username)

    if request.method == 'POST' and logics.check_email(request.POST['email']):
        print(request.POST)
        user.email = request.POST['email']
        confirm_email.send_confirm_email(user, request)
        user.confirm_email = False
        user.save()

    return render(request, 'email.html', {'user': user})


def activate_user_email(request, uid, token):
    try:
        uid = force_text(urlsafe_base64_decode(uid))
        user = models.SSUser.objects.get(pk=uid)
    except:
        user = None
    if user and confirm_email.account_activation_token.check_token(user, token):
        user.confirm_email = True
        user.save()
        return email(request)
    else:
        logout(request)
        return HttpResponseRedirect('/')

ss_main/templates/edit_shirt.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="margin-top: 10px">
    <div class="row justify-content-lg-center">
        <div class="col-4">
            <div class="shirt-item">
                 <input name="title" class="form-control" placeholder={{shirt.title}}>
                <br>
                <input name="description" class="form-control" placeholder={{shirt.description}}>
                <br>
                <label> {{shirt.creator}}</label>
                <label> Rating {{shirt.rating}}</label>
                <label class="value">{{shirt.value}}$</label>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ss_main/templates/main.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="margin-top: 10px">
    {% for three_shirt in shirts %}
    <div class="row">
        {% for shirt in three_shirt%}
        <div class="col-4">
            <div class="shirt-item">
                <a href="{% url 'ss_main:shirt' shirt_id=shirt.id%}"> {{shirt.title}} </a>
                <br>
                <label> Rating {{shirt.rating}}</label>
                <label class="value">{{shirt.value}} $</label>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock content %}

ss_main/templates/shirt.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="margin-top: 10px">
    <div class="row justify-content-lg-center">
        <div class="col-10">
            <div class="shirt-item">
                <label class="title">{{shirt.title}}</label>
                <br>
                <label> {{shirt.description}}</label>
                <br>
                <label> {{shirt.creator}}</label>
                <label> Rating {{shirt.rating}}</label>
                <label class="value">{{shirt.value}}$</label>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ss_users/templates/email.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="padding-top: 5%">
    <div class="row align-items-center">
        <div class="col-4"></div>
        <div class="col-4" style="background-image: linear-gradient(to right, slateblue, white); border-radius: 5%">
            <form class="form-group" action="" method="post">
                {% csrf_token %}
                <label style="color: #181a00; font-family: fantasy; font-size: 100%">
                    {% if user.confirm_email %}
                    If you want to change your mail, enter a new mail, an email will come with an activation link.
                    {% else %}
                    A message has been sent to your email with a link to activate your account.
                    {% endif %}
                </label>
                <div class="form-group">
                    Email:
                    <input name="email" type="email" class="form-control" placeholder={{request.user.email}}
                           minlength="3">
                </div>
                <button type="submit" class="btn btn-dark my-2 my-sm-0" style="background-color: #232323;
                border: none; margin-bottom: 10px"> Send mail-activator
                </button>
                <small class="form-text" style="color: #232323;"> If the letter did not arrive,
                    then check the correctness of the mail and resend the message.
                    Before activation, some functions will be unavailable.
                </small>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

ss_users/templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="container" style="margin-top: 5%">
    <div class="row align-items-center">
        <div class="col-4"></div>
        <div class="col-4" style="background-image: linear-gradient(slateblue 25%, white); border-radius: 5%">
            <form method="post" action="" class="form-group" style="margin-top: 10px">
                {% csrf_token %}
                <label style="color: #181a00; font-family: fantasy; font-size: 120%">
                    {{message}}
                </label>
                <div class="form-group">
                    <input name="username" class="form-control" placeholder="Username">
                </div>
                <div class="form-group">
                    <input type="password" name="password" value="" class="form-control" placeholder="Password">
                    <small class="form-text" style="color: #232323;">We'll never share your password with anyone else.
                    </small>
                </div>
                <button type="submit" class="btn btn-dark my-2 my-sm-0" style="background-color: #232323;
                border: none; margin-bottom: 10px">Log in
                </button>
                <small class="form-text" style="color: #232323">
                    You don't have an account?
                    <a href="{% url 'ss_users:registration'%}"> Sign up</a>
                </small>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

ss_users/templates/registration.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="margin-top: 5%; background-image: url('../static/bg_login.jpg')">
    <div class="row align-items-center">
        <div class="col-4"></div>
        <div class="col-4" style="background-image: linear-gradient(white, slateblue); border-radius: 5%">
            <form method="post" action="" class="form-group" style="margin-top: 10px">
                {% csrf_token %}
                <label style="color: #181a00; font-family: fantasy; font-size: 100%">
                    {{message}}
                </label>
                <div class="form-group">
                    <input name="username" type="username" class="form-control" placeholder="Username">
                </div>
                <div class="form-group">
                    <input name="email" type="email" class="form-control" placeholder="Email" minlength="3">
                </div>
                <div class="form-group">
                    <input name="password1" type="password" class="form-control" placeholder="Password">
                    <small class="form-text" style="color: #232323;">We'll never share your password with anyone else.
                    </small>
                </div>
                <div class="form-group">
                    <input name="password2" type="password" class="form-control" placeholder="Confirm the password">
                </div>

                <button type="submit" class="btn btn-dark my-2 my-sm-0" style="background-color: #232323;
                border: none; margin-bottom: 10px">Register
                </button>
                <small class="form" style="color: #232323; padding: auto">
                    You have an account?
                    <a href="{% url 'ss_users:login'%}" style="color: white;"> Sign in</a>
                </small>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

ss_users/templates/user_page.html
{% extends "base.html" %}

{% block content %}
<div>
    <div class="container" style="margin-top: 10px">
        HELLO, {{user.username}}
        <br>
        User id: {{user.id}}
        <br>
        Confirm Email: {{user.confirm_email}}
        {% for shirt in shirts%}
        <div class="row justify-content-lg-center">
            <div class="col-6">
                <div class="shirt-item">
                    <label class="title">{{shirt.title}}</label>
                    <br>
                    <label> Rating {{shirt.rating}}</label>
                    <label class="value">{{shirt.value}}$</label>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon"
          href="https://ae01.alicdn.com/kf/HTB1RHepOpXXXXbJaFXXq6xXFXXXB/poop-emoji-3d.jpg_640x640.jpg"
          type="image/jpg">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Shit|Shirt</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background: slateblue">
    <a class="navbar-brand" href="{% url 'ss_main:main'%}">
        <img src="https://ae01.alicdn.com/kf/HTB1RHepOpXXXXbJaFXXq6xXFXXXB/poop-emoji-3d.jpg_640x640.jpg" width="30"
             height="30" class="d-inline-block align-top" alt="">
        Shit|Shirt
    </a>
    <div class="collapse navbar-collapse" id="navbarNav1">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#"> Shirts <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
    </div>
    <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav2">
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ss_users:logout' %}">Log out</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ss_users:user_page' user_id=request.user.id %}">My Profile</a>
            </li>
            {% if request.user.is_superuser %}
            <li class="nav-item active">
                <a class="nav-link" href="admin">Administration</a>
            </li>
            {% endif %}
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ss_users:login' %}">Log in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ss_users:registration' %}">Sign up</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}
{% endblock content %}
<div class="card fixed-bottom inline-group" style="background-color: slateblue; border-radius: 0px">
    <div class="card-header" style="font-size: 14px">
        <div class="d-flex " style="color: white "> Efi-fi Inc. ITransition Inc. {% now "Y M" %}</div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>